import { User, Post } from './types';

export const dummyUsers: User[] = [
    {
        id: '1',
        username: 'sarah_chen',
        name: 'Sarah Chen',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/1.jpg',
        bio: 'Software engineer | Coffee enthusiast ☕ | Building cool things with React Native',
    },
    {
        id: '2',
        username: 'mike_johnson',
        name: 'Mike Johnson',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/2.jpg',
        bio: 'Tech lead @StartupXYZ | Passionate about clean code and mentoring',
    },
    {
        id: '3',
        username: 'emily_rodriguez',
        name: 'Emily Rodriguez',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/3.jpg',
        bio: 'UX Designer turned Developer | Creating beautiful mobile experiences 🎨',
    },
    {
        id: '4',
        username: 'alex_kim',
        name: 'Alex Kim',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/4.jpg',
        bio: 'Full-stack developer | Open source contributor | Always learning 📚',
    },
    {
        id: '5',
        username: 'jessica_taylor',
        name: 'Jessica Taylor',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/5.jpg',
        bio: 'Mobile dev enthusiast | Tech blogger | Dog mom 🐕',
    },
];

export const dummyUser: User = dummyUsers[0];

export const dummyPosts: Post[] = [
    {
        id: '1',
        createdAt: '2024-12-13T08:30:00Z',
        heading: 'First React Native Deployment! 🚀',
        content: 'Just deployed my first React Native app! The feeling is incredible. Thanks to everyone who helped me along the way!',
        category: 'Content Creation',
        user_id: '1',
        user: dummyUsers[0],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '2',
        createdAt: '2024-12-13T09:15:00Z',
        heading: 'Re: First React Native Deployment',
        content: 'Congratulations! 🎉 What kind of app did you build?',
        category: 'Content Creation',
        user_id: '2',
        user: dummyUsers[1],
        parent_id: '1',
        parent: null,
        replies: [],
    },
    {
        id: '3',
        createdAt: '2024-12-13T10:00:00Z',
        heading: 'Re: First React Native Deployment',
        content: 'That\'s awesome! The first deployment is always special 💪',
        category: 'Content Creation',
        user_id: '3',
        user: dummyUsers[2],
        parent_id: '1',
        parent: null,
        replies: [],
    },
    {
        id: '4',
        createdAt: '2024-12-12T14:20:00Z',
        heading: 'The Art of Deleting Code',
        content: 'Working on a new feature today. Sometimes the best code is the code you delete 🗑️ Keeping things simple and maintainable is an art form. #CleanCode',
        category: 'Faith',
        user_id: '2',
        user: dummyUsers[1],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '5',
        createdAt: '2024-12-12T15:45:00Z',
        heading: 'Re: The Art of Deleting Code',
        content: 'So true! Less is more when it comes to maintainable code.',
        category: 'Faith',
        user_id: '4',
        user: dummyUsers[3],
        parent_id: '4',
        parent: null,
        replies: [],
    },
    {
        id: '6',
        createdAt: '2024-12-12T11:30:00Z',
        heading: 'State Management Dilemma',
        content: 'Anyone else struggle with choosing the right state management solution? Redux, MobX, Zustand... so many options! Each has its pros and cons. 🤔',
        category: 'Content Creation',
        user_id: '3',
        user: dummyUsers[2],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '7',
        createdAt: '2024-12-12T12:00:00Z',
        heading: 'Re: State Management Dilemma',
        content: 'I\'ve been loving Zustand lately! Simple and powerful.',
        category: 'Content Creation',
        user_id: '1',
        user: dummyUsers[0],
        parent_id: '6',
        parent: null,
        replies: [],
    },
    {
        id: '8',
        createdAt: '2024-12-11T16:30:00Z',
        heading: 'Clean Code Book Review',
        content: 'Just finished reading "Clean Code" by Robert Martin. Mind blown! 🤯 Every developer should read this. The principles are timeless.',
        category: 'Health',
        user_id: '4',
        user: dummyUsers[3],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '9',
        createdAt: '2024-12-11T09:00:00Z',
        heading: 'Good Morning Devs!',
        content: 'Morning coffee and coding session ☕💻 What are you all working on today?',
        category: 'Health',
        user_id: '5',
        user: dummyUsers[4],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '10',
        createdAt: '2024-12-11T09:30:00Z',
        heading: 'Re: Good Morning Devs!',
        content: 'Building a custom tab bar component! It\'s looking pretty good so far 😊',
        category: 'Health',
        user_id: '1',
        user: dummyUsers[0],
        parent_id: '9',
        parent: null,
        replies: [],
    },
    {
        id: '11',
        createdAt: '2024-12-10T13:45:00Z',
        heading: 'TypeScript in React Native',
        content: 'Hot take: TypeScript makes React Native development so much better. The type safety is worth the extra setup! 🛡️ Catches bugs before they happen.',
        category: 'Music',
        user_id: '2',
        user: dummyUsers[1],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '12',
        createdAt: '2024-12-10T14:00:00Z',
        heading: 'Re: TypeScript in React Native',
        content: '100% agree! Caught so many bugs before runtime thanks to TypeScript.',
        category: 'Music',
        user_id: '4',
        user: dummyUsers[3],
        parent_id: '11',
        parent: null,
        replies: [],
    },
    {
        id: '13',
        createdAt: '2024-12-10T10:20:00Z',
        heading: 'Discovering Expo Router',
        content: 'Just discovered Expo Router and I\'m impressed! File-based routing in React Native feels so natural 🎯 Makes navigation so much cleaner.',
        category: 'Music',
        user_id: '3',
        user: dummyUsers[2],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '14',
        createdAt: '2024-12-09T17:00:00Z',
        heading: 'Friday Wins!',
        content: 'Friday deployment done! ✅ Time to relax for the weekend. You all have a great one! 🎉',
        category: 'Faith',
        user_id: '5',
        user: dummyUsers[4],
        parent_id: null,
        parent: null,
        replies: [],
    },
    {
        id: '15',
        createdAt: '2024-09-08T08:15:00Z',
        heading: 'Developer Life',
        content: 'Debugging is like being a detective in a crime movie where you are also the murderer 🕵️‍♂️😅 #DevLife',
        category: 'Faith',
        user_id: '4',
        user: dummyUsers[3],
        parent_id: null,
        parent: null,
        replies: [],
    },
];
